[package]
edition = "2021"
name = "udp-screech"
version = "0.1.0"

[dependencies]
igd = "0.12.0"
my_internet_ip = "0.1.1"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
